services:
  - type: web
    name: football-app
    runtime: node
    plan: free
    branch: main
    buildCommand: npm ci && npm run build -w server && npm run build -w client && npm run db:deploy -w server && npm run db:seed -w server
    startCommand: npm run start -w server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        sync: false
      - key: FOOTBALL_DATA_TOKEN
        sync: false
        value: ""
    autoDeploy: true
